In [10]:
import numpy as np

In [9]:
x=np.array([[1,2], [1,2]])
print("matrix 1:")
print(x)
y=np.array([[4,5], [8,9]])
print("matrix 2:")
print(y)
z=x+y
print("\n matrix A+B:")
print(z)


matrix 1:
[[1 2]
 [1 2]]
matrix 2:
[[4 5]
 [8 9]]

 matrix A+B:
[[ 5  7]
 [ 9 11]]
